### ISSUE TITLE
畫面會出現scroll bar

### ISSUE THREAD

**Issue by Misphix** [denpaio/denpaio#1]
- OS: Windows 10 Home build 1703(x64)
- Browser: Chrome 58.0.3029.81 (64-bit)
- Display Resolution: 1366 * 768
![image](https://cloud.githubusercontent.com/assets/6009748/25525547/02ad1a66-2c42-11e7-9c08-957f164fb6c8.png)

**Comment by shikendon** [comment]
現在捲動軸應該只在內容過長的時候才會出現，麻煩再幫忙確認一下沒問題就 close 這個 issue 謝謝。

之後會改用 `slimScroll` 替代 Windows 上的捲動軸，但目前 slimScroll 只有 jQuery 版本，原生 JS 版本目前只有找到一個 [slim-scroll](https://github.com/kamlekar/slim-scroll) 評價一百多顆星星，暫時再觀望看看如果真的沒有更好的就只好用它了。
