### ISSUE TITLE
在Search輸入空白會出現空白的Dialog Box

### ISSUE THREAD

**Issue by Misphix** [denpaio/denpaio#2]
- Browser: Chrome 58.0.3029.81 (64-bit)
![image](https://cloud.githubusercontent.com/assets/6009748/25525694/b4b32f48-2c42-11e7-89bd-ebcb189cceb4.png)

**Comment by shikendon** [comment]
這裡因為沒有輸入關鍵字造成 `ITunes.music` 報錯，目前已經修改為沒有輸入關鍵字的時候改列出電台現有歌曲（`Track`）。

TODO:
 - [ ] 搜尋進度條
 - [ ] 找不到任何歌曲的提示訊息

等以上 TODO 完成的時候再 close 這個 issue。
