### ISSUE TITLE
I can't click searching bar when I use mobile browser

### ISSUE THREAD

**Issue by Misphix** [denpaio/denpaio#3]
OS: Android 5.0
Browser: Chrome 58.0.3029.83
![screenshot_2017-05-04-09-06-33](https://cloud.githubusercontent.com/assets/6009748/25687549/e8799e04-303c-11e7-9a42-b93379a50c1f.png)

**Comment by shikendon** [comment]
Now audio player shows scrollbar when content overflowed. It's ugly, but it works.
